### ISSUE TITLE
TypeError: Cannot read property '0' of undefined after update to version 3.0.2

### ISSUE THREAD

**Issue by tab00** [okgrow/analytics#197]
I got the following error after updating to the latest version and re-running my app:

TypeError: Cannot read property '0' of undefined
    at toDosPath (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:41:8)
    at C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:98:16
    at Array.map (native)
    at Function._.map._.collect (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:97:56)
    at C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:95:16
    at ImportScanner._getRelativeImportId (C:\tools\isobuild\import-scanner.js:525:43)
    at C:\tools\isobuild\import-scanner.js:509:33
    at _.each._.forEach (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._resolve (C:\tools\isobuild\import-scanner.js:498:7)
    at C:\tools\isobuild\import-scanner.js:564:29
    at _.each._.forEach (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:357:14
    at Array.forEach (native)
    at ImportScanner.scanImports (C:\tools\isobuild\import-scanner.js:355:22)
    at C:\tools\isobuild\compiler-plugin.js:1040:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:1008:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1059:8)
    at C:\tools\isobuild\bundler.js:830:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:821:18)
    at C:\tools\isobuild\bundler.js:2881:14
    at C:\tools\isobuild\bundler.js:2970:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\-\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2969:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2862:31)
    at C:\tools\isobuild\bundler.js:2809:32
    at Object.withCache (C:\tools\fs\files.js:1693:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2809:16)
    at C:\tools\runners\run-app.js:583:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:582:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:626:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:885:28)
    at C:\tools\runners\run-app.js:412:12

Then when I downgraded to version 3.0.1 my app worked again.

**Comment by RichardLitt** [comment]
I'm not sure that this is a problem with analytics. It looks like an issue with meteor-tool. 

@cfnelson Any idea on this one?

**Comment by cfnelson** [comment]
@tab00 As a temp work around please revert back to `okgrow:analytics@3.0.1`. We believe the issue is related to changes in Meteors build processes in v1.5+. We will be opening an issue over on meteor's repo to try to better understand the cause.

**Comment by cfnelson** [comment]
@RichardLitt I opened an issue up on [meteor](https://github.com/meteor/meteor/issues/9193), however I am unsure if it's a bug with the Meteor build tool or an issue due to the way we published this package. Hopefully someone will respond to the issue and provide some insight. 🔥

**Comment by RichardLitt** [comment]
@cfnelson Doesn't look like this should have been caused on our end. Hope we get some light on this! Cool problem.

**Comment by cfnelson** [comment]
@tab00 We have released `v3.0.3` please update to the latest and everything should be working again! 🎉  😃  The update also includes two fixes to the `data.title` for usage with react-router + react-helmet and the `referrer` now behaves as aspected when using back/fwd buttons. 🔥
